name: Rust

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - '**'

  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build node project
      working-directory: ./services/node/src/
      run: cargo build --verbose

    - name: Run tests in node project
      working-directory: ./services/node/src/
      run: cargo test --verbose
